---
root: true
parser: @babel/eslint-parser
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
env:
  es6: true
  browser: true
rules:
  semi: off
  no-unused-vars:
    - "error"
    - { argsIgnorePattern: "^_" }
